services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
